### ISSUE TITLE
sqlboiler --version outputs incorrect version [v4.9.0]

### ISSUE THREAD

**Issue by crlssn** [aarondl/sqlboiler#1113] opened 2022-04-04 14:46 UTC
### What version of SQLBoiler are you using (`sqlboiler --version`)?
I have `v4.9.0` installed as confirmed by the newly added `AllEnum()` function but this command returns `v4.8.6`.

![Screenshot 2022-04-04 at 15 45 20](https://user-images.githubusercontent.com/4332122/161569453-d73d253a-27eb-4d14-913c-364068d70308.png)

**Comment by stephenafamo** [comment] 2022-04-05 08:04
1. I can confirm this behavior, and I understand why this happened, I originally tagged the wrong commit.
3. However, this is unexpected because I tagged the correct commit before it became available on pkg.go.dev (or so I thought).
4. Regardless, this should be fixed in the next release.

**Comment by crlssn** [comment] 2022-04-05 08:11
Thank you. Do you think it's worth releasing a patch with the correct behaviour? It may cause confusion within teams who previously had `v4.8.6` installed as the generated files also contains the wrong version number.
```
// Code generated by SQLBoiler 4.8.6 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
```

**Comment by stephenafamo** [comment] 2022-04-06 10:05
Should be within the next week.

**Comment by Serjlee** [comment] 2022-04-08 12:33
Hello @stephenafamo,  I was also affected by this, plus some weird checksum mismatches between me, a colleague and a CI server that caused quite the confusion. What about [retracting the version](https://go.dev/ref/mod#go-mod-file-retract) before the next release?

**Comment by stephenafamo** [comment] 2022-04-08 13:32
Great suggestion @Serjlee 

I have now made a release for `v4.9.1` which includes retracting `v4.9.0`

**Closed as completed by stephenafamo** 2022-04-08 13:32 UTC
